services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}  # Use values from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  nest_backend:
    build: .
    container_name: nest_backend
    restart: always
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres_db:${DB_PORT}/${DB_NAME}"  # Use values from .env
    ports:
      - "8000:8000"

  react_frontend:
    build:
      context: ../license-management-system-frontend  # Adjust this path if needed
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    depends_on:
      - nest_backend
    environment:
      REACT_APP_API_URL: "http://nest_backend:8000"  # Ensure frontend connects to backend inside Docker network
    ports:
      - "3000:3000"
volumes:
  pg_data:
