export enum OrganizationType {
  LISENCE_ISSUER = 'LICENSE_ISSUER',
  EMONEY = 'EMONEY',
  REMITTANCE = 'REMITTANCE',
  PAYMENT_AGGREGATOR = 'PAYMENT_AGGREGATOR',
  PAYMENT_SYSTEM_OPERATOR = 'PAYMENT_SYSTEM_OPERATOR',
  CHEQUE_PRINTING_COMPANY = 'CHEQUE_PRINTING_COMPANY',
  CSD_STOCK_BROKER = 'CSD_STOCK_BROKER',
}
