export enum UserType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ORG_ADMIN = 'ORG_ADMIN',
  LICENSE_MANAGER = 'LICENSE_MANAGER',
  END_USER = 'END_USER',
  CONTRACT_MANAGER = 'CONTRACT_MANAGER',
  LICENSE_OWNER = 'LICENSE_OWNER',
}
